version: '3.3'
services:

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./Moveip:/var/www/moveip.ru
    depends_on:
      - php-fpm

  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

  php-fpm:
    environment:
      ENVIRONMENT: "local"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./Moveip:/var/www/moveip.ru
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    depends_on:
      - docker-host

  php-fpm-ws:
    environment:
      ENVIRONMENT: "local"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./Moveip:/var/www/moveip.ru
    build:
      context: ./docker/php-ws
    ports:
      - "9001:9000"
    depends_on:
      - docker-host


  redis:
    image: redis
    command:
      - 'redis-server'
      - '--maxmemory ${REDIS_MAXMEM:-1024mb}'
      - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
      - '--requirepass simple'
      - '--notify-keyspace-events Egx'
    volumes:
      - ./storage/redis/data:/data
    ports:
      - "6379:6379"