version: '3.3'
services:

    web-websocket:
      image: nginx:latest
      ports:
        - "8123:80"
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/websocket:/etc/nginx/sites-available
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
        - ./Moveip:/var/www/moveip.ru
      depends_on:
        - php-fpm
      links:
        - php-fpm
      networks:
        - moveip-network

    web:
      image: nginx:latest
      ports:
        - "8000:80"
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/sites-available:/etc/nginx/sites-available
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
        - ./Moveip:/var/www/moveip.ru
      depends_on:
        - php-fpm
      links:
        - php-fpm
      networks:
        - moveip-network

    docker-host:
      image: qoomon/docker-host
      cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
      restart: on-failure
      networks:
        - moveip-network



    redis:
      image: redis
      command:
        - 'redis-server'
        - '--maxmemory ${REDIS_MAXMEM:-1024mb}'
        - '--maxmemory-policy ${REDIS_POLICY:-noeviction}'
        - '--requirepass simple'
        - '--notify-keyspace-events Egx'
      volumes:
        - ./storage/redis/data:/data
      ports:
        - "6379:6379"
      links:
        - php-fpm
      networks:
        - moveip-network




    php-fpm:
      environment:
        ENVIRONMENT: "local"
      volumes:
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        - ./Moveip:/var/www/moveip.ru
      build:
        context: ./docker/php
      ports:
        - "9000:9000"
        - "5500:5500"
      depends_on:
        - docker-host
      expose:
        - "5500"
      networks:
        - moveip-network

networks:
  moveip-network:
    driver: bridge